services:
  app:
    build: .
    container_name: avaliador_app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama:11434 
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama 

  iniciador_modelos:
    image: ollama/ollama:latest
    container_name: iniciador_modelos
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    # Substitui a trava padrão pelo terminal
    entrypoint: /bin/sh
    # O sinal "|" avisa que o que vem abaixo é um script de texto único
    command: 
      - -c
      - |
        sleep 5
        ollama pull qwen3:0.6b
        ollama pull nomic-embed-text

volumes:
  ollama_data: